use std::ffi::OsStr;
use std::path::Path;

pub(crate) enum FileType {
    Json,
    Xml,
    Gzip,
    Zip,
    Tar,
    Rar,
    SevenZip,
    Bzip,
    Bzip2,
    Xz,
    Pdf,
    Jar,
    Epub,
    RichText,
    MSWord,
    LegacyMSWord,
    OpenDocumentText,
    MSExcel,
    LegacyMSExcel,
    OpenDocumentSpreadsheet,
    MSPowerPoint,
    LegacyMSPowerPoint,
    OpenDocumentPresentation,
    Mp3,
    Midi,
    WebMAudio,
    Wav,
    Aac,
    Mp4,
    WebMVideo,
    Avi,
    Jpeg,
    Png,
    Gif,
    Svg,
    Tiff,
    Webp,
    PlainText,
    Html,
    Css,
    Javascript,
    Csv,
    GoogleAudio,
    GoogleDocs,
    GoogleDriveThirdPartyShortcut,
    GoogleDrawing,
    GoogleDriveFile,
    GoogleDriveFolder,
    GoogleForm,
    GoogleFusionTable,
    GoogleJamboard,
    GoogleEmailLayout,
    GoogleMyMaps,
    GooglePhotos,
    GoogleSlides,
    GoogleAppScript,
    GoogleShortcut,
    GoogleSites,
    GoogleSheets,
    GoogleUnknown,
    GoogleVids,
    GoogleVideo,
    Unknown,
}

impl FileType {
    pub(crate) fn mime(&self) -> &str {
        match self {
            FileType::Json => "application/json",
            FileType::Xml => "application/xml",
            FileType::Gzip => "application/gzip",
            FileType::Zip => "application/zip",
            FileType::Tar => "application/x-tar",
            FileType::Rar => "application/vnd.rar",
            FileType::SevenZip => "application/x-7z-compressed",
            FileType::Bzip => "application/x-bzip",
            FileType::Bzip2 => "application/x-bzip2",
            FileType::Xz => "application/x-xz",
            FileType::Pdf => "application/pdf",
            FileType::Jar => "application/java-archive",
            FileType::Epub => "application/epub+zip",
            FileType::RichText => "application/rtf",
            FileType::MSWord => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            FileType::LegacyMSWord => "application/msword",
            FileType::OpenDocumentText => "application/vnd.oasis.opendocument.text",
            FileType::MSExcel => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            FileType::LegacyMSExcel => "application/vnd.ms-excel",
            FileType::OpenDocumentSpreadsheet => "application/vnd.oasis.opendocument.spreadsheet",
            FileType::MSPowerPoint => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            FileType::LegacyMSPowerPoint => "application/vnd.ms-powerpoint",
            FileType::OpenDocumentPresentation => "application/vnd.oasis.opendocument.presentation",
            FileType::Mp3 => "audio/mpeg",
            FileType::Midi => "audio/midi",
            FileType::WebMAudio => "audio/webm",
            FileType::Wav => "audio/wav",
            FileType::Aac => "audio/aac",
            FileType::Mp4 => "video/mp4",
            FileType::WebMVideo => "video/webm",
            FileType::Avi => "video/x-ms-video",
            FileType::Jpeg => "image/jpeg",
            FileType::Png => "image/png",
            FileType::Gif => "image/gif",
            FileType::Svg => "image/svg+xml",
            FileType::Tiff => "image/tiff",
            FileType::Webp => "image/webp",
            FileType::PlainText => "text/plain",
            FileType::Html => "text/html",
            FileType::Css => "text/css",
            FileType::Javascript => "application/javascript",
            FileType::Csv => "text/csv",
            FileType::GoogleAudio => "application/vnd.google-apps.audio",
            FileType::GoogleDocs => "application/vnd.google-apps.document",
            FileType::GoogleDriveThirdPartyShortcut => "application/vnd.google-apps.drive-sdk",
            FileType::GoogleDrawing => "application/vnd.google-apps.drawing",
            FileType::GoogleDriveFile => "application/vnd.google-apps.file",
            FileType::GoogleDriveFolder => "application/vnd.google-apps.folder",
            FileType::GoogleForm => "application/vnd.google-apps.form",
            FileType::GoogleFusionTable => "application/vnd.google-apps.fusiontable",
            FileType::GoogleJamboard => "application/vnd.google-apps.jam",
            FileType::GoogleEmailLayout => "application/vnd.google-apps.mail-layout",
            FileType::GoogleMyMaps => "application/vnd.google-apps.map",
            FileType::GooglePhotos => "application/vnd.google-apps.photo",
            FileType::GoogleSlides => "application/vnd.google-apps.presentation",
            FileType::GoogleAppScript => "application/vnd.google-apps.script",
            FileType::GoogleShortcut => "application/vnd.google-apps.shortcut",
            FileType::GoogleSites => "application/vnd.google-apps.site",
            FileType::GoogleSheets => "application/vnd.google-apps.spreadsheet",
            FileType::GoogleVids => "application/vnd.google-apps.vid",
            FileType::GoogleVideo => "application/vnd.google-apps.video",
            FileType::GoogleUnknown => "application/vnd.google-apps.unknown",
            FileType::Unknown => "application/octet-stream"
        }
    }

    pub(crate) fn from_filename(filename: &str) -> Self {
        let path = Path::new(filename)
            .extension()
            .unwrap_or(OsStr::new(""))
            .to_str()
            // If the extension cannot be read on UTF-8, it treats as Unknown file.
            // It is ok due to the Unknown is mapped as 'application/octet-stream'.
            // This can cover almost all case generically.
            .unwrap_or("");

        match path {
            "json" => FileType::Json,
            "xml" => FileType::Xml,
            "gz" | "tgz" => FileType::Gzip,
            "zip" => FileType::Zip,
            "tar" => FileType::Tar,
            "rar" => FileType::Rar,
            "7z" => FileType::SevenZip,
            "bz" => FileType::Bzip,
            "bz2" => FileType::Bzip2,
            "xz" => FileType::Xz,
            "pdf" => FileType::Pdf,
            "jar" => FileType::Jar,
            "epub" => FileType::Epub,
            "rtf" => FileType::RichText,
            "docx" => FileType::MSWord,
            "odt" => FileType::OpenDocumentText,
            "doc" => FileType::LegacyMSWord,
            "xlsx" => FileType::MSExcel,
            "ods" => FileType::OpenDocumentSpreadsheet,
            "xls" => FileType::LegacyMSExcel,
            "pptx" => FileType::MSPowerPoint,
            "odp" => FileType::OpenDocumentPresentation,
            "ppt" => FileType::LegacyMSPowerPoint,
            "mp3" => FileType::Mp3,
            "mid" | "midi" => FileType::Midi,
            "weba" => FileType::WebMAudio,
            "wav" => FileType::Wav,
            "aac" => FileType::Aac,
            "mp4" => FileType::Mp4,
            "webm" => FileType::WebMVideo,
            "avi" => FileType::Avi,
            "jpeg" | "jpg" | "jpe" | "jfif" | "jif" => FileType::Jpeg,
            "png" => FileType::Png,
            "gif" => FileType::Gif,
            "svg" => FileType::Svg,
            "tif" | "tiff" => FileType::Tiff,
            "webp" => FileType::Webp,
            "txt" | "text" => FileType::PlainText,
            "html" | "htm" => FileType::Html,
            "css" => FileType::Css,
            "js" | "mjs" => FileType::Javascript,
            "csv" => FileType::Csv,
            _ => FileType::Unknown
        }
    }
    
    pub(crate) fn from_mime(mime: &str) -> Self {
        match mime {
            "application/json" => FileType::Json,
            "application/xml" | "text/xml" => FileType::Xml,
            "application/gzip" => FileType::Gzip,
            "application/zip" => FileType::Zip,
            "application/x-tar" => FileType::Tar,
            "application/vnd.rar" => FileType::Rar,
            "application/x-7z-compressed" => FileType::SevenZip,
            "application/x-bzip" => FileType::Bzip,
            "application/x-bzip2" => FileType::Bzip2,
            "application/x-xz" => FileType::Xz,
            "application/pdf" => FileType::Pdf,
            "application/java-archive" => FileType::Jar,
            "application/epub+zip" => FileType::Epub,
            "application/rtf" => FileType::RichText,
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document" => FileType::MSWord,
            "application/msword" => FileType::LegacyMSWord,
            "application/vnd.oasis.opendocument.text" => FileType::OpenDocumentText,
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" => FileType::MSExcel,
            "application/vnd.ms-excel" => FileType::LegacyMSExcel,
            "application/vnd.oasis.opendocument.spreadsheet" => FileType::OpenDocumentSpreadsheet,
            "application/vnd.openxmlformats-officedocument.presentationml.presentation" => FileType::MSPowerPoint,
            "application/vnd.ms-powerpoint" => FileType::LegacyMSPowerPoint,
            "application/vnd.oasis.opendocument.presentation" => FileType::OpenDocumentPresentation,
            "audio/mpeg" => FileType::Mp3,
            "audio/midi" => FileType::Midi,
            "audio/webm" => FileType::WebMAudio,
            "audio/wav" => FileType::Wav,
            "audio/aac" => FileType::Aac,
            "video/mp4" => FileType::Mp4,
            "video/webm" => FileType::WebMVideo,
            "video/x-ms-video" => FileType::Avi,
            "image/jpeg" => FileType::Jpeg,
            "image/png" => FileType::Png,
            "image/gif" => FileType::Gif,
            "image/svg+xml" => FileType::Svg,
            "image/tiff" => FileType::Tiff,
            "image/webp" => FileType::Webp,
            "text/plain" => FileType::PlainText,
            "text/html" => FileType::Html,
            "text/css" => FileType::Css,
            "application/javascript" | "text/javascript" => FileType::Javascript,
            "text/csv" => FileType::Csv,
            "application/vnd.google-apps.audio" => FileType::GoogleAudio,
            "application/vnd.google-apps.document" => FileType::GoogleDocs,
            "application/vnd.google-apps.drive-sdk" => FileType::GoogleDriveThirdPartyShortcut,
            "application/vnd.google-apps.drawing" => FileType::GoogleDrawing,
            "application/vnd.google-apps.file" => FileType::GoogleDriveFile,
            "application/vnd.google-apps.folder" => FileType::GoogleDriveFolder,
            "application/vnd.google-apps.form" => FileType::GoogleForm,
            "application/vnd.google-apps.fusiontable" => FileType::GoogleFusionTable,
            "application/vnd.google-apps.jam" => FileType::GoogleJamboard,
            "application/vnd.google-apps.mail-layout" => FileType::GoogleEmailLayout,
            "application/vnd.google-apps.map" => FileType::GoogleMyMaps,
            "application/vnd.google-apps.photo" => FileType::GooglePhotos,
            "application/vnd.google-apps.presentation" => FileType::GoogleSlides,
            "application/vnd.google-apps.script" => FileType::GoogleAppScript,
            "application/vnd.google-apps.shortcut" => FileType::GoogleShortcut,
            "application/vnd.google-apps.site" => FileType::GoogleSites,
            "application/vnd.google-apps.spreadsheet" => FileType::GoogleSheets,
            "application/vnd.google-apps.vid" => FileType::GoogleVids,
            "application/vnd.google-apps.video" => FileType::GoogleVideo,
            "application/vnd.google-apps.unknown" => FileType::GoogleUnknown,
            _ => FileType::Unknown,
        }

    }
}
